/* =========================================================================
 * mock-data.js — fake NDFD + MRMS data for Phase 2 interactive preview
 * Phase 3 replaces this entire file with `fetch()` calls to live JSON
 * generated by the cron job.
 * ========================================================================= */

window.DEFNS_MOCK = (function () {
  'use strict';

  // ---- NDFD forecast precipitation polygons (mocked) ----------------------
  // Three polygons over WNC at varying categories. Shapes are illustrative,
  // not geographically meaningful - the cron job will produce real ones.
  const NDFD_FORECAST = {
    type: 'FeatureCollection',
    features: [
      // High accumulation (cat 11 = 5-6") - small intense storm core
      {
        type: 'Feature',
        properties: { category: 11, label: '5.00\u20136.00\u2033' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.85, 35.40],
            [-82.55, 35.40],
            [-82.55, 35.60],
            [-82.85, 35.60],
            [-82.85, 35.40]
          ]]
        }
      },
      // Moderate accumulation (cat 6 = 1.5-2") - broader band
      {
        type: 'Feature',
        properties: { category: 6, label: '1.50\u20132.00\u2033' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-83.20, 35.20],
            [-82.20, 35.20],
            [-82.20, 35.80],
            [-83.20, 35.80],
            [-83.20, 35.20]
          ]]
        }
      },
      // Light edge (cat 2 = .25-.50") - outer fringe of the system
      {
        type: 'Feature',
        properties: { category: 2, label: '.25\u2013.50\u2033' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-83.80, 34.90],
            [-81.50, 34.90],
            [-81.50, 36.20],
            [-83.80, 36.20],
            [-83.80, 34.90]
          ]]
        }
      }
    ],
    meta: {
      issued:        '2026-05-21T11:00:00Z',
      window_end:    '2026-05-21T23:00:00Z',
      window_hours:  12,
      source:        'NDFD'
    }
  };

  // ---- MRMS 1-hour observed precipitation (mocked) ------------------------
  // More fragmented than NDFD - radar sees real cells, not smoothed
  // forecast bins. Three small polygons at different intensities.
  const MRMS_OBSERVED = {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        properties: { category: 8, label: '2.50\u20133.00\u2033' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.70, 35.55],
            [-82.60, 35.55],
            [-82.60, 35.62],
            [-82.70, 35.62],
            [-82.70, 35.55]
          ]]
        }
      },
      {
        type: 'Feature',
        properties: { category: 5, label: '1.00\u20131.50\u2033' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.80, 35.45],
            [-82.55, 35.45],
            [-82.55, 35.65],
            [-82.80, 35.65],
            [-82.80, 35.45]
          ]]
        }
      },
      {
        type: 'Feature',
        properties: { category: 2, label: '.25\u2013.50\u2033' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.95, 35.30],
            [-82.40, 35.30],
            [-82.40, 35.70],
            [-82.95, 35.70],
            [-82.95, 35.30]
          ]]
        }
      }
    ],
    meta: {
      observed_at:   '2026-05-21T14:00:00Z',
      window_hours:  1,
      source:        'MRMS MultiSensor Pass1',
      max_inches:    2.84,
      minutes_ago:   32
    }
  };

  // ---- Debris flow polygons (mocked subset for testing intersection) ------
  // In Phase 3 these come from the NCGS AGOL FeatureServer via esri-leaflet.
  // For Phase 2, a handful of polygons over WNC, some inside the precip
  // polygons (will appear flagged) and some outside (won't).
  const DEBRIS_FLOWS = {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        properties: { OBJECTID: 1001, county: 'Buncombe' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.65, 35.52],
            [-82.62, 35.52],
            [-82.62, 35.55],
            [-82.65, 35.55],
            [-82.65, 35.52]
          ]]
        }
      },
      {
        type: 'Feature',
        properties: { OBJECTID: 1002, county: 'Henderson' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.50, 35.45],
            [-82.46, 35.45],
            [-82.46, 35.48],
            [-82.50, 35.48],
            [-82.50, 35.45]
          ]]
        }
      },
      {
        type: 'Feature',
        properties: { OBJECTID: 1003, county: 'Madison' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.78, 35.85],
            [-82.74, 35.85],
            [-82.74, 35.88],
            [-82.78, 35.88],
            [-82.78, 35.85]
          ]]
        }
      },
      {
        type: 'Feature',
        properties: { OBJECTID: 1004, county: 'Haywood' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.95, 35.50],
            [-82.92, 35.50],
            [-82.92, 35.53],
            [-82.95, 35.53],
            [-82.95, 35.50]
          ]]
        }
      },
      {
        type: 'Feature',
        properties: { OBJECTID: 1005, county: 'Transylvania' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.75, 35.20],
            [-82.71, 35.20],
            [-82.71, 35.23],
            [-82.75, 35.23],
            [-82.75, 35.20]
          ]]
        }
      },
      {
        type: 'Feature',
        properties: { OBJECTID: 1006, county: 'Yancey' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.30, 35.95],
            [-82.27, 35.95],
            [-82.27, 35.98],
            [-82.30, 35.98],
            [-82.30, 35.95]
          ]]
        }
      },
      {
        type: 'Feature',
        properties: { OBJECTID: 1007, county: 'Mitchell' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-82.10, 36.05],
            [-82.07, 36.05],
            [-82.07, 36.08],
            [-82.10, 36.08],
            [-82.10, 36.05]
          ]]
        }
      },
      {
        type: 'Feature',
        properties: { OBJECTID: 1008, county: 'Avery' },
        geometry: {
          type: 'Polygon',
          coordinates: [[
            [-81.90, 36.10],
            [-81.87, 36.10],
            [-81.87, 36.13],
            [-81.90, 36.13],
            [-81.90, 36.10]
          ]]
        }
      }
    ]
  };

  return { NDFD_FORECAST, MRMS_OBSERVED, DEBRIS_FLOWS };
})();
